### PR TITLE
Check `Sprint` field in PR

### LINKED ISSUE #45: Check Sprint field in PRs
When [conform-pr GitHub Action](https://github.com/FerretDB/github-actions/tree/main/conform-pr) checks some pull request, it should fail if the Sprint field (in all projects where it exists) is empty ~or has a value that is not the "current" one~.

### PR DESCRIPTION
**Pull request by ronaudinho**
Closes #45 .

Currently checks if `Sprint` field is set to current one if exists, not sure if necessary, as depending on implementation plan for #53, may be checking only if the title matches would suffice?

### CODE REVIEW

File: internal/graphql/pull_request_test.go [hunk 1]
```diff
@@ -72,3 +73,46 @@ func TestPullRequest(t *testing.T) {
...
+func TestIsCurrentIteration(t *testing.T) {
+	startDate := func(n int) string {
+		return time.Now().Add(time.Duration(n*24) * time.Hour).Format("2006-01-02")
+	}
+	cases := []struct {
+		name      string
+		startDate string
+		want      bool
+	}{
+		{
```
Comment (AlekSi) [inline internal/graphql/pull_request_test.go:86]:
```suggestion
	}{{
```

File: internal/graphql/pull_request.go [hunk 2]
```diff
@@ -222,3 +237,18 @@ func (c *Client) GetPullRequest(ctx context.Context, nodeID string) *PullRequest
 
 	return res
 }
+
+// isCurrentIteration checks if given startDate is current iteration.
+func isCurrentIteration(startDate string, duration int) bool {
```
Comment (AlekSi) [inline internal/graphql/pull_request.go:242]: Yeah, let's remove that for now, and always use the value returned by GitHub API

File: conform-pr/main.go [hunk 3]
```diff
@@ -169,6 +173,23 @@ func checkSize(_ *githubactions.Action, projectFields map[string]graphql.Fields)
...
+// checkSprint checks if PR is in for current sprint.
+func checkSprint(_ *githubactions.Action, projectFields map[string]graphql.Fields) error {
+	// sort projects to make results stable
+	projects := maps.Keys(projectFields)
+	slices.Sort(projects)
+
+	for _, project := range projects {
+		if sprint, ok := projectFields[project]["Sprint"]; ok {
+			if sprint == "" {
+				return fmt.Errorf("PR for project %s is not set/is not current sprint", project)
```
Comment (AlekSi) [inline conform-pr/main.go:185]:
```suggestion
				return fmt.Errorf("PR for project %q is not set, project)
```

File: conform-pr/main_test.go [hunk 4]
```diff
@@ -46,13 +46,15 @@ func TestRunPRChecks(t *testing.T) {
...
 			{check: "Size", err: nil},
+			{check: "Sprint", err: nil},
 		},
 	}, {
 		name:   "ProjectV2",
 		nodeID: "PR_kwDOGfwnTc48u60R", // https://github.com/FerretDB/github-actions/pull/85
 		expected: []checkResult{
 			{check: "Labels", err: nil},
 			{check: "Size", err: fmt.Errorf("PR for project Another test project has size 🐋 X-Large")},
+			{check: "Sprint", err: fmt.Errorf("PR for project Another test project is not set/is not current sprint")},
```
Comment (AlekSi) [inline conform-pr/main_test.go:57]:
```suggestion
			{check: "Sprint", err: fmt.Errorf(`PR for project "Another test project" is not set`)},
```

File: internal/graphql/pull_request.go (hunk 2 above)
Comment (AlekSi) [reply internal/graphql/pull_request.go:242]: ^

Comment (AlekSi) [reply internal/graphql/pull_request.go:242]: @ronaudinho poke :)

**Review by AlekSi — APPROVED** [review]
